# Generated by Django 3.0 on 2019-12-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_django', '0003_auto_20191209_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=180),
        ),
    ]
